name: Deploy to Railway

on:
  push:
    branches:
      - main # or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

- name: Deploy to Railway
  env:
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  run: railway up -- --help
